before:
  hooks:
    - go mod download
builds:
- env:
  - GO111MODULE=on
  ldflags:
    - -X {{.Env.LD_FLAGS}}
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}-beta_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
nfpm:
  vendor: jbvm.io
  homepage: https://www.jbvm.io/
  maintainer: Jimmy Bonds <[jbonds@jbvm.io]>
  description: CLI for Apache Kafka Management
  license: Apache 2.0
  formats:
    - deb
    - rpm
  name_template: "{{ .ProjectName }}_{{ .Version }}-beta_{{ .Os }}_{{ .Arch }}"
release:
  disable: false
  prerelease: true
  name_template: "{{ .Tag }}-beta"
snapshot:
  name_template: "{{ .Env.TRAVIS_BRANCH }}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  goos: linux
  dockerfile: Dockerfile
  - image_templates:
  - "jbvmio/kafkactl:{{ .Tag }}"
  binaries:
  - kafkactl
  build_flag_templates:
  - "--label=maintainer=jbvm.io"