language: go
go:
- 1.11.x
before_install:
- eval $(./envvars)
- export FNAME_STATIC=$(echo $FNAME)
- export LD_FLAGS_STATIC=$(echo $LD_FLAGS)
env:
  global:
  - GO111MODULE=on
  - secure: "rhX4sCsYXAi4o/HfZ4b7v//aC0c/ShKXpxkJHuSrP8iZ/vjhtMW1jU9TBH8HNhqMmpw+kWiQRHRCCA2C9NPe2Mv1+j4Z44IJKU0Ux8OIqJYVqOcJcRXiKCghPxM9nfYm4iz4oTGFOXte9v6PXFpztpOp7D9ax5+PDSFoWBCPAaWQkKVMMVP4TlGAWdWE4i+KztxvSQSIshAfOm/2PT/jgUlFX9//rSldmT4Q6tUGR1ZXkiEIgz9ZkY2c1swi+OQSvbGojW4X7QlugPxAf5y/NGFwXRjgKFzTk5MWBxEJy8HCziD57OD/KyHoQjWSO1YZ5f9fiHmqgfHeBreQme/d8YrWRIMzytYlB+YuwVJgsJt+rGvgzruBpzSlxqsH/Ly0YXCGpL6WFC3j9ZOCTcPIFMJn9rDF//1pUoAlH2lYEf6CAiqRZrcq8zt1u0ggiS71sRDrB6SM2uml00t/afXs4wfY4gNuxrAXaBdxuno+0okbiuTyd0POBiRmZvMOnm4F8OxzrxcB8Z4xzK/wDqgftcjm2LTNcmI1zOZNmJQvgmmU7fbcfTLX9HX0nOXetyCndbUQcC5iIeVof66W5ctDJMvDSSEMhpuf1OKCouTdn/kjEJjyPYBjIrcyBOKuw2twjBgxXx8dR/7D8p66t+/CtevyWsz/RYGyK+4M9imoslo="
  - secure: "ixMpb2sdhJiy8y9yacJ+jrg9OEmv7TaHmR+QNRKRT4m3KCTJkDpsVRPWNMEh9nsgRbw50TPqG/BCJz0kIy1GnaYf9Z0piAvmGBd29i0YVtLIEhfEVT3rd1LC+9hOamHzU42R0/xn0ZCnawaBUDbZBDdExZ464AITYHKLal3xmh8HGDx+qlGuQZVCnfm5+zGWTajbh+GV92LR4yjz/iJjHeu57cbrZl3MiKEaX1nOFKO5hliG/MYp97Oehy2ezLlEHNgJVfXQG1Z+IgyJC7kWZIbusGmDTbFoFA5MMBEKQvQsnlJk8ysiNIKcBcVCrQBx8VIzr+w3rTcAbI2Orkbpxp5RrsLYHZ91iBX8EQxp6Ut/grtrASVwIrUQzpfMbngzwxOxkvrg4m34QI1/o0nFE/K6XDTJwi7ugeQgWpt5FXhfLV+JnHAETxGzI/PHvPdhGFkgXUcUrYA1ErDJWzufZ2LWZ+2Nuetkc+7KZUhRfAtw3XMl8WLsWSbt6V3atxmUUjZTPN2R3NbyNMpOvbYJmA/CCk3O7SbboQuyxM4apECGg+ou6B6Qk4a4Bdg7ItleiuWWrHRzras3eTUmhLK+07SAwUG4Lbo524h10+azbl4Pdkico5NlEwtR5NfQ869ItpkCjamjINh/fKpmDYHpLfqQJY6xS2luvw7A9etpZZI="
addons:
  apt:
    packages:
    - rpm
services:
- docker
script: make extest
after_success:
- test -n "$TRAVIS_TAG" && docker login -u=jbvmio -p="$DOCKER_PASSWORD"
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux