language: go
go:
- 1.11.x
env:
  global:
  - GO111MODULE=on
  - PUBRELEASE=false
  - YTIME="1546300800"
  - LATEST=$(curl -s https://github.com/jbvmio/kafkactl/releases/latest | awk -F '/' '/releases/{print $8}' | awk -F '"' '{print $1}')
  - LATESTMAJ=$(echo $LATEST | cut -d '.' -f 1)
  - LATESTMIN=$(echo $LATEST | cut -d '.' -f 2)
  - LATESTPAT=$(echo $LATEST | cut -d '.' -f 3)
  - NEXTPAT=$(echo $LATESTPAT + 1 | bc)
  - NEXTVER="${LATESTMAJ}.${LATESTMIN}.${NEXTPAT}"
  - BT=$(date +%s)
  - GCT=$(git rev-list -1 HEAD --timestamp | awk '{print $$1}')
  - GC=$(git rev-list -1 HEAD --abbrev-commit)
  - REV=$(echo "$GCT - $YTIME" | bc)
  - FNAME="${LATEST}-beta.${REV}"
  - LD_FLAGS="github.com/jbvmio/kafkactl/cli/cmd.latestMajor=${LATESTMAJ} -X github.com/jbvmio/kafkactl/cli/cmd.latestMinor=${LATESTMIN} -X github.com/jbvmio/kafkactl/cli/cmd.latestPatch=${LATESTPAT} -X github.com/jbvmio/kafkactl/cli/cmd.release=${PUBRELEASE} -X github.com/jbvmio/kafkactl/cli/cmd.nextRelease=${NEXTVER} -X github.com/jbvmio/kafkactl/cli/cmd.revision=${REV} -X github.com/jbvmio/kafkactl/cli/cmd.buildTime=${BT} -X github.com/jbvmio/kafkactl/cli/cmd.commitHash=${GC}"
  - FNAME_STATIC=$(echo $FNAME)
  - LD_FLAGS_STATIC=$(echo $LD_FLAGS)
  - secure: "ixMpb2sdhJiy8y9yacJ+jrg9OEmv7TaHmR+QNRKRT4m3KCTJkDpsVRPWNMEh9nsgRbw50TPqG/BCJz0kIy1GnaYf9Z0piAvmGBd29i0YVtLIEhfEVT3rd1LC+9hOamHzU42R0/xn0ZCnawaBUDbZBDdExZ464AITYHKLal3xmh8HGDx+qlGuQZVCnfm5+zGWTajbh+GV92LR4yjz/iJjHeu57cbrZl3MiKEaX1nOFKO5hliG/MYp97Oehy2ezLlEHNgJVfXQG1Z+IgyJC7kWZIbusGmDTbFoFA5MMBEKQvQsnlJk8ysiNIKcBcVCrQBx8VIzr+w3rTcAbI2Orkbpxp5RrsLYHZ91iBX8EQxp6Ut/grtrASVwIrUQzpfMbngzwxOxkvrg4m34QI1/o0nFE/K6XDTJwi7ugeQgWpt5FXhfLV+JnHAETxGzI/PHvPdhGFkgXUcUrYA1ErDJWzufZ2LWZ+2Nuetkc+7KZUhRfAtw3XMl8WLsWSbt6V3atxmUUjZTPN2R3NbyNMpOvbYJmA/CCk3O7SbboQuyxM4apECGg+ou6B6Qk4a4Bdg7ItleiuWWrHRzras3eTUmhLK+07SAwUG4Lbo524h10+azbl4Pdkico5NlEwtR5NfQ869ItpkCjamjINh/fKpmDYHpLfqQJY6xS2luvw7A9etpZZI="
addons:
  apt:
    packages:
    - rpm
    - bc
services:
- docker
script: make extest
after_success:
- test -n "$TRAVIS_TAG" && docker login -u=jbvmio -p="$DOCKER_PASSWORD"
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux